[rule]
description = """
Identifies an unexpected process accessing the password store of commonly used web browsers. Adversaries may steal
credentials from web browsers by reading files specific to the target browser.
"""
id = "f488cd1b-2407-4ec8-8705-7adf99ccbd33"
license = "Elastic License v2"
name = "Web Browser Credential Access via Unusual Process"
os_list = ["windows"]
version = "1.0.30"

query = '''
file where event.type == "access" and
 process.executable != null and
 file.name : ("Login Data", "logins.json", "signons.sqlite", "cookies.sqlite") and
 file.path : ("?:\\Users\\*", "\\??\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\Users\\*") and
 (
  process.code_signature.trusted == false or
  process.code_signature.exists == false or
  process.name : ("rundll32.exe", "regsvr32.exe", "powershell.exe") or
  process.executable :
                ("?:\\Users\\Public\\*",
                 "?:\\Users\\*\\Downloads\\*",
                 "?:\\Windows\\Temp\\*",
                 "?:\\Windows\\Tasks\\*",
                 "?:\\ProgramData\\*",
                 "?:\\Windows\\Microsoft.NET\\*")
  ) and
  not process.code_signature.status : ("errorExpired", "errorCode_endpoint*") and
  not (process.code_signature.subject_name : 
              ("Opera Norway AS", "Keeper Security Inc.", "Mozilla Corporation", "Google LLC", "BrowserWorks Ltd", "SAP SE", "Emsisoft Ltd") and
       process.code_signature.trusted == true) and
  not (process.code_signature.subject_name : "Shift Technologies Inc." and process.code_signature.status : "errorUntrustedRoot") and 
  not user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and
  not process.executable : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*", "C:\\Telivy\\telivy_agent_2.3.2.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\MsMpEng.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*\\MpCopyAccelerator.exe",
                            "?:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Platform\\*\\MsSense.exe",
                            "?:\\ProgramData\\Spillman\\Spillman\\application\\FlexClient\\WebView2\\msedgewebview2.exe",
                            "?:\\ProgramData\\EPSecClient\\*\\EPSecClient_setup.exe",
                            "?:\\ProgramData\\CTES\\Components\\DARAgent\\CSDARAgent.exe",
                            "?:\\ProgramData\\PerfectLaw\\DMS\\WebView2Runtime\\msedgewebview2.exe",
                            "?:\\Users\\*\\AppData\\Local\\Carbonate\\Carbonate\\Application\\Carbonate.exe",
                            "?:\\Users\\*\\Documents\\Chromium\\chrome.exe") and process.pid != 4 and
  not (process.name : "gener8.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\GENER8\\USER DATA\\DEFAULT\\LOGIN DATA") and
  not (process.name : "ccs.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ENTERPRISEBANKSECUREBROWSER\\USER DATA\\DEFAULT\\LOGIN DATA") and 
  not (process.name : "epic.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\EPIC PRIVACY BROWSER\\USER DATA\\DEFAULT\\LOGIN DATA") and
  not (process.name : "ccss?st.exe" and file.path : "?:\\USERS\\*\\APPDATA\\LOCAL\\ESERVISSECUREBROWSER\\USER DATA\\DEFAULT\\LOGIN DATA") and 
  not (process.name : "chrome.exe" and 
      file.path : ("?:\\USERS\\*\\APPDATA\\LOCAL\\CHROMIUM\\USER DATA\\DEFAULT\\LOGIN DATA", 
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PLAYWRIGHT_CHROMIUMDEV_PROFILE-*\\DEFAULT\\LOGIN DATA")) and 
  not file.path : ("?:\\USERS\\*\\APPDATA\\ROAMING\\BURPSUITE\\PRE-WIRED-BROWSER\\DEFAULT\\LOGIN DATA",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PUPPETEER_DEV_CHROME_PROFILE-*\\DEFAULT\\LOGIN DATA",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\PGADMIN4\\USER DATA\\DEFAULT\\LOGIN DATA",
                   "?:\\USERS\\*\\UNGOOGLED-CHROMIUM-PORTABLE\\DATA\\DEFAULT\\LOGIN DATA",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\TEMP\\PUPPETEER_DEV_CHROME_PROFILE-*\\DEFAULT\\LOGIN DATA",
                   "?:\\Users\\*\\chrome-device\\Default\\Login Data",
                   "?:\\Users\\*\\EBWebView\\Default\\Login Data",
                   "?:\\Users\\*\\Favorites\\BOOKMARKS\\Default\\Login Data",
                   "?:\\USERS\\*\\APPDATA\\LOCAL\\ELROND\\MAIAR\\USER DATA\\DEFAULT\\LOGIN DATA", 
                   "?:\\Users\\*\\AppData\\Local\\Microsoft\\Edge\\Default BackupDD\\Login Data", 
                   "?:\\Users\\*\\Favorites\\bookmarks\\Default\\Login Data")
'''

min_endpoint_version = "8.1.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1539"
name = "Steal Web Session Cookie"
reference = "https://attack.mitre.org/techniques/T1539/"

[[threat.technique]]
id = "T1555"
name = "Credentials from Password Stores"
reference = "https://attack.mitre.org/techniques/T1555/"
[[threat.technique.subtechnique]]
id = "T1555.003"
name = "Credentials from Web Browsers"
reference = "https://attack.mitre.org/techniques/T1555/003/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.1.0"
