[rule]
description = """
Identifies suspicious memory intrusion events originating from an exception handler. This may be the result of an
evasion attempt to evade memory scanners while performing malicious code injection.
"""
id = "20b374bd-2288-48f1-ad70-fa498e69e164"
license = "Elastic License v2"
name = "VirtualProtect via Vectored Exception Handling"
os_list = ["windows"]
reference = ["https://github.com/lem0nSec/ShellGhost"]
version = "1.0.1"

query = '''
api where process.Ext.api.behaviors : ("execute_fluctuation", "hollow_unbacked") and

 process.Ext.api.name == "VirtualProtect" and
 
 /* an exception call stack pattern to match before the full arraysearch  */
 process.thread.Ext.call_stack_summary: "ntdll.dll|*|ntdll.dll|*" and 

 /* provenance metadata exists */
 process.thread.Ext.call_stack_final_user_module.code_signature != null and

 /* abusing exception handlers for proxying memory manip */
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "*ntdll.dll!KiUserExceptionDispatcher*") and

 /* final user module is unsigned or signed with an untrusted code signature */
 _arraysearch(process.thread.Ext.call_stack_final_user_module.code_signature, $entry, $entry.trusted == false or $entry.exists == false) and

 not process.thread.Ext.call_stack_final_user_module.hash.sha256 : "fdb0c7af2ab2e821787222517531068ad01e333fe91e54d59bb80a8f49eb0bec"
'''

min_endpoint_version = "8.10.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
